/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ifnmg.edu.br.telas;

import ifnmg.edu.br.credential.Credential;

public class telaPrincipal extends javax.swing.JFrame {

    private static telaPrincipal instance;
    
    public telaPrincipal() {
        initComponents();
    }
    
    public static telaPrincipal getInstance(Credential credential) {

        if (instance == null) {
            instance = new telaPrincipal();
        }

        //<editor-fold defaultstate="collapsed" desc="Ativação/Desativação de menus">
        //admin
        if(credential.getUser().getRole().getName().equals("administrador")){
            instance.setTitle("Bem vindo - " + credential.getUser().getName());
        }else
        if(credential.getUser().getRole().getName().equals("bibliotecario")){
            instance.mniCadastrarUser.setVisible(false);
            instance.mniEditarUser.setVisible(false);
            instance.mniSeparadorUser.setVisible(false);
            instance.mniAdmUser.setVisible(false);
            instance.mniSeparador1User.setVisible(false);
            instance.mniAutorizarEmp.setVisible(false);
            instance.setTitle("Bem vindo - " + credential.getUser().getName());
        }else{
            instance.mniCadastrarUser.setVisible(false);
            instance.mniEditarUser.setVisible(false);
            instance.mniSeparadorUser.setVisible(false);
            instance.mniAdmUser.setVisible(false);
            instance.mniSeparador1User.setVisible(false);
            instance.mniNovoEmp.setVisible(false);
            instance.mniEditarEmp.setVisible(false);
            instance.mniNovoLiv.setVisible(false);
            instance.setTitle("Bem vindo - " + credential.getUser().getName());
        }
        //instance.mnuCadastroUsuario.setEnabled(credencial.isAdministrador());
        //</editor-fold>
        return instance;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnUsuario = new javax.swing.JMenu();
        mniCadastrarUser = new javax.swing.JMenuItem();
        mniEditarUser = new javax.swing.JMenuItem();
        mniSeparadorUser = new javax.swing.JPopupMenu.Separator();
        mniAdmUser = new javax.swing.JMenuItem();
        mniSeparador1User = new javax.swing.JPopupMenu.Separator();
        mniDesconect = new javax.swing.JMenuItem();
        mnEmprestimo = new javax.swing.JMenu();
        mniNovoEmp = new javax.swing.JMenuItem();
        mniAutorizarEmp = new javax.swing.JMenuItem();
        mniEditarEmp = new javax.swing.JMenuItem();
        mniHistEmp = new javax.swing.JMenuItem();
        mnLivro = new javax.swing.JMenu();
        mniNovoLiv = new javax.swing.JMenuItem();
        mniBuscarLiv = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Aplicação");
        setName("TelaPrincipal"); // NOI18N
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 613, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 367, Short.MAX_VALUE)
        );

        mnUsuario.setText("Usuario");

        mniCadastrarUser.setText("Cadastrar");
        mnUsuario.add(mniCadastrarUser);

        mniEditarUser.setText("Editar");
        mnUsuario.add(mniEditarUser);
        mnUsuario.add(mniSeparadorUser);

        mniAdmUser.setText("Administrador");
        mnUsuario.add(mniAdmUser);
        mnUsuario.add(mniSeparador1User);

        mniDesconect.setText("Desconectar");
        mniDesconect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniDesconectActionPerformed(evt);
            }
        });
        mnUsuario.add(mniDesconect);

        jMenuBar1.add(mnUsuario);

        mnEmprestimo.setText("Emprestimo");

        mniNovoEmp.setText("Novo");
        mniNovoEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniNovoEmpActionPerformed(evt);
            }
        });
        mnEmprestimo.add(mniNovoEmp);

        mniAutorizarEmp.setText("Autorizar");
        mnEmprestimo.add(mniAutorizarEmp);

        mniEditarEmp.setText("Editar");
        mnEmprestimo.add(mniEditarEmp);

        mniHistEmp.setText("Historico");
        mnEmprestimo.add(mniHistEmp);

        jMenuBar1.add(mnEmprestimo);

        mnLivro.setText("Livro");

        mniNovoLiv.setText("Novo");
        mnLivro.add(mniNovoLiv);

        mniBuscarLiv.setText("Buscar");
        mnLivro.add(mniBuscarLiv);

        jMenuBar1.add(mnLivro);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mniDesconectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniDesconectActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new telaLogin().setVisible(true);
    }//GEN-LAST:event_mniDesconectActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        setVisible(false);
        new telaLogin().setVisible(true);
    }//GEN-LAST:event_formWindowClosed

    private void mniNovoEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniNovoEmpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mniNovoEmpActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(telaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new telaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu mnEmprestimo;
    private javax.swing.JMenu mnLivro;
    private javax.swing.JMenu mnUsuario;
    private javax.swing.JMenuItem mniAdmUser;
    private javax.swing.JMenuItem mniAutorizarEmp;
    private javax.swing.JMenuItem mniBuscarLiv;
    private javax.swing.JMenuItem mniCadastrarUser;
    private javax.swing.JMenuItem mniDesconect;
    private javax.swing.JMenuItem mniEditarEmp;
    private javax.swing.JMenuItem mniEditarUser;
    private javax.swing.JMenuItem mniHistEmp;
    private javax.swing.JMenuItem mniNovoEmp;
    private javax.swing.JMenuItem mniNovoLiv;
    private javax.swing.JSeparator mniSeparador1User;
    private javax.swing.JPopupMenu.Separator mniSeparadorUser;
    // End of variables declaration//GEN-END:variables
}
